apiVersion: v1                          # API versi untuk resource Service
kind: Service                           # Mendefinisikan resource Service
metadata:
  name: order-service                   # Nama service
  namespace: ecommerce                  # Namespace tempat service dibuat

spec:
  selector:
    app: order                          # Pilih pod dengan label app=order
  ports:
    - protocol: TCP                     # Protokol yang digunakan
      port: 3000                        # Port yang dibuka oleh service