# Menentukan API version untuk resource Namespace
apiVersion: v1
# Menentukan jenis resource Kubernetes yang didefinisikan
kind: Namespace
# Menyediakan informasi terkait metadata resource
metadata:
  name: ecommerce                     # Nama namespace
  labels:
    name: ecommerce                   # Label yang terkait dengan namespace
    istio-injection: enabled          # Mengaktifkan Istio sidecar injection pada namespace ini
---
# Menentukan API version untuk resource Namespace
apiVersion: v1
# Menentukan jenis resource Kubernetes yang didefinisikan
kind: Namespace
# Menyediakan informasi terkait metadata resource
metadata:
  name: messaging                     # Nama namespace
  labels:
    name: messaging                   # Label yang terkait dengan namespace