version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install Hadolint
          command: |
            mkdir -p /home/circleci/bin
            curl -sSL https://github.com/hadolint/hadolint/releases/download/v2.8.0/hadolint-Linux-x86_64 -o /home/circleci/bin/hadolint
            chmod +x /home/circleci/bin/hadolint
            echo 'export PATH=$PATH:/home/circleci/bin' >> ~/.bashrc
            source ~/.bashrc
      - run:
          name: Run Hadolint on Dockerfile
          command: hadolint Dockerfile

  test-app:
    docker:
      - image: golang:1.18
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Build and push Docker image to GitHub Packages
          command: |
            # Login to GitHub Packages
            echo $GH_TOKEN | docker login ghcr.io -u $GH_USERNAME --password-stdin
            # Build the Docker image
            docker build -t ghcr.io/$GH_USERNAME/karsajobs:$CIRCLE_SHA1 .
            # Push the Docker image to GitHub Packages
            docker push ghcr.io/$GH_USERNAME/karsajobs:$CIRCLE_SHA1

workflows:
  version: 2
  karsajobs:
    jobs:
      - lint-dockerfile
      - test-app:
          requires:
            - lint-dockerfile
      - build-app-karsajobs:
          requires:
            - test-app
