# Bagian ini mengindikasikan API version dari Kubernetes resource
apiVersion: v1
# Bagian ini mengindikasikan jenis Kubernetes resource yang didefinisikan
kind: Service
# Bagian ini berisi informasi terkait resource dalam pengidentifikasian
metadata:
  name: rabbitmq-service
  namespace: messaging
# Bagian ini  mengindikasikan spesifikasi resource
spec:
  # Bagian ini berfungsi untuk memilih atau memfilter pod yang akan dikelolanya
  selector:
    app: rabbitmq
  # Mendefinisikan ports container berjalan
  ports:
    - protocol: TCP
      name: amqp
      port: 5672
      targetPort: 5672
    - protocol: TCP
      name: management
      port: 15672
      targetPort: 15672