# Menentukan API version untuk resource StatefulSet
apiVersion: apps/v1
# Menentukan jenis resource Kubernetes yang didefinisikan
kind: StatefulSet
# Menyediakan informasi terkait metadata resource
metadata:
  name: rabbitmq                    # Nama StatefulSet
  namespace: messaging               # Namespace tempat StatefulSet berada

# Menentukan spesifikasi resource
spec:
  # Selector untuk memilih pod dengan label app=rabbitmq
  selector:
    matchLabels:
      app: rabbitmq
  # Menentukan nama service yang terkait dengan StatefulSet
  serviceName: rabbitmq
  # Menentukan jumlah replika pod yang ingin dijalankan
  replicas: 1
  # Template untuk pod yang akan dibuat
  template:
    metadata:
      labels:
        app: rabbitmq
    # Spesifikasi resource untuk pod
    spec:
      # Menentukan container yang harus dijalankan di dalam pod
      containers:
        # Menentukan nama container
        - name: rabbitmq
          # Menentukan image yang digunakan untuk container
          image: rabbitmq:3.11-management
          # Kebijakan untuk mengunduh image hanya jika belum ada
          imagePullPolicy: IfNotPresent
          # Mendefinisikan port yang akan digunakan oleh container
          ports:
            - containerPort: 5672        # Port AMQP untuk RabbitMQ
              name: amqp
            - containerPort: 15672       # Port manajemen RabbitMQ
              name: management
          # Menentukan volume yang akan dipasang di container
          volumeMounts:
            - name: data-volume         # Nama volume
              mountPath: /data/rabbitmq # Lokasi mount di dalam container
          # Menentukan probe untuk memeriksa kesiapan container
          readinessProbe:
            # Jenis probe menggunakan perintah shell
            exec:
              command:
                - sh
                - -c
                - rabbitmq-diagnostics status # Perintah yang dijalankan untuk memeriksa status RabbitMQ
            # Waktu penundaan sebelum probe dijalankan pertama kali
            initialDelaySeconds: 10
            # Interval antara tiap probe
            periodSeconds: 10
            # Waktu maksimal untuk probe agar selesai
            timeoutSeconds: 5
      # Daftar volume yang digunakan dalam pod
      volumes:
        # Menentukan volume yang akan digunakan oleh pod
        - name: data-volume
          # Menggunakan PersistentVolumeClaim untuk mengikat volume
          persistentVolumeClaim:
            # Nama PVC yang digunakan
            claimName: rabbitmq-pvc