# Menentukan API version untuk resource Service
apiVersion: v1
# Menentukan jenis resource Kubernetes yang didefinisikan
kind: Service
# Menyediakan informasi terkait metadata resource
metadata:
  name: rabbitmq-service               # Nama Service
  namespace: messaging                 # Namespace tempat Service berada

# Menentukan spesifikasi resource
spec:
  # Selector untuk memilih pod dengan label app=rabbitmq
  selector:
    app: rabbitmq
  # Mendefinisikan port yang digunakan oleh service
  ports:
    - protocol: TCP                    # Protokol yang digunakan (TCP)
      name: amqp                        # Nama port (AMQP untuk RabbitMQ)
      port: 5672                        # Port yang terbuka untuk service
      targetPort: 5672                  # Port yang digunakan pada container
    - protocol: TCP                    # Protokol yang digunakan (TCP)
      name: management                  # Nama port untuk manajemen RabbitMQ
      port: 15672                       # Port untuk manajemen
      targetPort: 15672                 # Port yang digunakan pada container